base_images:
  ocp_4.19_base-rhel9:
    name: "4.20"
    namespace: ocp
    tag: base-rhel9
  ocp_builder_rhel-9-golang-1.23-openshift-4.19:
    name: builder
    namespace: ocp
    tag: rhel-9-golang-1.23-openshift-4.19
build_root:
  from_repository: true
images:
- dockerfile_path: images/cli/Dockerfile.rhel
  inputs:
    ocp_4.19_base-rhel9:
      as:
      - registry.ci.openshift.org/ocp/4.19:base-rhel9
    ocp_builder_rhel-9-golang-1.23-openshift-4.19:
      as:
      - registry.ci.openshift.org/ocp/builder:rhel-9-golang-1.23-openshift-4.19
  to: cli
- dockerfile_literal: |
    FROM cli
    RUN set -eo pipefail
    RUN yum -y install yum-plugin-copr
    RUN yum -y install https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
    RUN yum -y copr enable ocm/tools
    RUN yum install -y jq ocm-cli make git
  from: cli
  to: cli-ocm
promotion:
  to:
  - additional_images:
      latest: cli-ocm
    excluded_images:
    - '*'
    name: cli-ocm
    namespace: ci
resources:
  '*':
    requests:
      cpu: "3"
      memory: 6Gi
zz_generated_metadata:
  branch: master
  org: openshift
  repo: oc
  variant: supplemental-images
