apiVersion: v1
kind: List
items:
- kind: ImageStream
  apiVersion: image.openshift.io/v1
  metadata:
    name: content-mirror
    namespace: ci
  spec:
    lookupPolicy:
      local: false
    tags:
    - name: latest
      from:
        kind: DockerImage
        name: "quay.io/openshift/ci:ci_content-mirror_latest"
      referencePolicy:
        type: Source
- kind: BuildConfig
  apiVersion: build.openshift.io/v1
  metadata:
    name: content-mirror
    namespace: ci
  spec:
    successfulBuildsHistoryLimit: 1
    failedBuildsHistoryLimit: 2
    output:
      to:
        kind: "DockerImage"
        name: "quay.io/openshift/ci:ci_content-mirror_latest"
    source:
      git:
        ref: main
        uri: https://github.com/openshift/content-mirror.git
      type: Git
    strategy:
      dockerStrategy:
        imageOptimizationPolicy: SkipLayers
        pullSecret:
          name: registry-push-credentials-ci-images-mirror
      type: Docker
    triggers:
    - type: ConfigChange
    - type: GitHub
      github:
        secretReference:
          name: github-deploymentconfig-trigger
